cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommercial.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercial/urls.py
from django.urls import path
from . import views

app_name = 'ecommercial'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_password/', views.update_password, name='update_password'),
    path('product/<int:pk>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'),
    path('category_summary/', views.category_summary, name='category_summary'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('search/', views.search, name='search'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from ecommercial.models import Product
from django.http import JsonResponse
from django.contrib import messages

def cart_summary(request):
    # Get the cart.
    cart = Cart(request)
    cart_products = cart.get_prods()
    quantities = cart.get_quants
    totals = cart.cart_total()
    return render(request, 'cart/cart_summary.html', {'cart_products': cart_products, "quantities": quantities, "totals": totals})



def cart_add(request):
    # Get the cart.
    cart = Cart(request)
    # Test for POST.
    if request.POST.get('action') == 'post':
        # Get stuff.
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        #Look up product in the database.
        product = get_object_or_404(Product, pk=product_id)
        # Save to our session.
        cart.add(product=product, quantity=product_qty)

        # Cet cart quantity.
        cart_quantity = cart.__len__()

        # Return a response.
        # response = JsonResponse({'Product Name': product_name})
        response = JsonResponse({'qty': cart_quantity})
        messages.success(request, 'Product added to cart...')
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        # Get stuff.
        product_id = int(request.POST.get('product_id'))
        # Call delete function in cart.
        cart.delete(product=product_id)

        response = JsonResponse({'product': product_id})
        messages.success(request, 'Item deleted from shopping cart...')
        return response
        # return redirect('cart:cart_summary')

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        # Get stuff.
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        cart.update(product=product_id, quantity=product_qty)

        response = JsonResponse({'qty':product_qty})
        messages.success(request, 'You cart has been updated...')
        return response
        #return redirect('cart:cart_summary')

cart/templates/cart/cart_summary.html
{% extends 'ecommercial/base.html' %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shopping Cart</h1>
                <p class="lead fw-normal text-white-50 mb-0">View Your Cart...</p>
            </div>
        </div>
    </header>
    <br/>
    <div class="container">
        {% if cart_products %}
            {% for product in cart_products %}
                <div class="card mb-3">
                  <div class="row g-0">
                    <div class="col-md-4">
                      <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <center>
                        <h5 class="card-title">{{ product.name }}</h5>
                          <br/>
                        <p class="card-text justified">{{ product.description }}</p>


                          {% if product.is_sale %}
                          <div class="d-flex justify-content-center small
                          text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>

                            <strike>
                                ${{ product.price }}
                            </strike>
                            &nbsp;
                            ${{ product.sale_price }}
                            <br/>
                            In: {{ product.category }}

                          {% else %}
                              {{ product.price }}
                          {% endif %}
                            <br/><br/>
                            <div class="row justify-content-center">
                            <div class="col-md-2">Quantity</div>
                            <div class="col-md-2">
                               <select class="form-select form-select-sm" id="select{{ product.id }}">

                                   {% for key, value in quantities.items %}
                                        {% if key == product.id|slugify %}
                                            <option selected>{{ value }}</option>
                                        {% endif %}
                                   {% endfor %}

                                   <option value="1">1</option>
                                   <option value="2">2</option>
                                   <option value="3">3</option>
                                   <option value="3">4</option>
                                   <option value="3">5</option>
                               </select>
                            </div>
            </div>

                          <br/><br/>
                          <a href="{% url 'ecommercial:home' %}" class="btn btn-secondary">Home</a>
                            <button type="button" data-index="{{ product.id }}"
                                    class="btn btn-secondary update-cart">Update
                            </button>

                            <button type="button" data-index="{{ product.id }}"
                                    class="btn btn-danger delete-product">Remove
                            </button>

                        </center>
                    </div>
                    </div>
                    </div>
                      </div>
                <br/>
            {% endfor %}

        <h3>${{ totals }}</h3>

        {% else %}
          There is Nothing in Your Cart...
          <br/><br/><br/><br/><br/><br/><br/><br/><br/>
        {% endif %}

    </div>



<script>
    // Update cart.
    $(document).on('click', '.update-cart', function (e){
        e.preventDefault();
        // grab the product id.
        var productid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: "{% url 'cart:cart_update' %}",
            data: {
                product_id: $(this).data('index'),
                product_qty: $('#select' + productid + 'option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'

            },
            success: function(json){
                //console.log(json)
                //document.getElementById("cart_quantity").textContent = json.qty
                location.reload();
            },
            error: function(xhr, errmsg, err){

            }
        });


    })




     // Delete item from cart.
    $(document).on('click', '.delete-product', function (e){
        e.preventDefault();
        // grab the product id.
        //var productid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: "{% url 'cart:cart_delete' %}",
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'

            },
            success: function(json){
                //console.log(json)
                //document.getElementById("cart_quantity").textContent = json.qty
                location.reload();
            },
            error: function(xhr, errmsg, err){

            }
        });


    })

</script>

{% endblock content %}