cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommercial.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommercial/urls.py
from django.urls import path
from . import views

app_name = 'ecommercial'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_password/', views.update_password, name='update_password'),
    path('product/<int:pk>', views.product, name='product'),
    path('category/<str:foo>', views.category, name='category'),
    path('category_summary/', views.category_summary, name='category_summary'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('search/', views.search, name='search'),
]

ecommercial/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    phone = models.CharField(max_length=12, blank=True)
    address1 = models.CharField(max_length=100, blank=True, default='')
    address2 = models.CharField(max_length=100, blank=True, default='')
    city = models.CharField(max_length=200, blank=True)
    state = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username

# Create a user Profile by default when a user signs up.
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
# Automate the profile thing.
post_save.connect(create_profile, sender=User)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=0)
    description = models.CharField(max_length=300, default='', blank=True, null=True)
    image = models.ImageField(upload_to='uploads/product/')
    is_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, max_digits=6, decimal_places=2)

    # Add sales stuff.
    def __str__(self):
        return self.name

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100, blank=True, default='')
    phone = models.CharField(max_length=20, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.product

ecommercial/forms.py
from cProfile import label

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django import forms

from ecommercial.models import Profile


class UserInfoForm(forms.ModelForm):
	phone = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}), required=False)
	address1 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 1'}), required=False)
	address2 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 2'}), required=False)
	city = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}), required=False)
	state = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'State'}), required=False)
	zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zipcode'}), required=False)
	country = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country'}), required=False)

	class Meta:
		model = Profile
		fields = ('phone', 'address1', 'address2', 'city', 'state', 'zipcode', 'country')



class ChangePasswordForm(SetPasswordForm):
	class Meta:
		model = User
		fields = ['new_password1', 'new_password2']

	def __init__(self, *args, **kwargs):
		super(ChangePasswordForm, self).__init__(*args, **kwargs)

		self.fields['new_password1'].widget.attrs['class'] = 'form-control'
		self.fields['new_password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['new_password1'].label = ''
		self.fields['new_password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['new_password2'].widget.attrs['class'] = 'form-control'
		self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['new_password2'].label = ''
		self.fields['new_password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

class UpdateUserForm(UserChangeForm):
	# Hide password stuff.
	password = None
	# Get other fields.
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}), required=False)
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}), required=False)
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}), required=False)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

	def __init__(self, *args, **kwargs):
		super(UpdateUserForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields[
			'username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'


class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

ecommercial/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Profile
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, UpdateUserForm, ChangePasswordForm, UserInfoForm
from django import forms

# Create your views here.

def update_info(request):
    if request.user.is_authenticated:
        current_user = Profile.objects.get(user__id=request.user.id)
        form = UserInfoForm(request.POST or None, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(request, "Your Info has been updated!!!")
            return redirect('ecommercial:home')

        return render(request, "ecommercial/update_info.html", {"form": form})
    else:
        messages.success(request, "You Must be Logged In to Access That Page!!!")
        return redirect('ecommercial:home')


def update_password(request):
    if request.user.is_authenticated:
        current_user = request.user
        # Did they fill out the form.
        if request.method == 'POST':
            form = ChangePasswordForm(current_user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Your password has been updated!')
                # login(request, current_user)
                return redirect('ecommercial:login')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                    return redirect('ecommercial:update_password')

        else:
            form = ChangePasswordForm(current_user)
            return render(request, "ecommercial/update_password.html", {'form': form})
    else:
        messages.success(request, "You Must be Logged in to Access That Page!!!")
        return redirect('ecommercial:home')


def update_user(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        user_form = UpdateUserForm(request.POST or None, instance=current_user)
        if user_form.is_valid():
            user_form.save()

            login(request, current_user)
            messages.success(request, "Profile has been updated!!!")
            return redirect('ecommercial:home')

        return render(request, "ecommercial/update_user.html", {"user_form": user_form})
    else:
        messages.success(request, "You Must be Logged in to Access That Page!!!")
        return redirect('ecommercial:home')

def category_summary(request):
    categories = Category.objects.all()
    return render(request, 'ecommercial/category_summary.html', {"categories": categories})

def category(request, foo):
    # Replace Hyphens with spaces.
    #foo = foo.replace("-", " ")
    # Grab the category from the url.
    try:
        # Look up the Category.
        category = Category.objects.get(name=foo)
        products = Product.objects.filter(category=category)
        return render(request, 'ecommercial/category.html', {'products': products, 'category': category})

    except:
        messages.success(request, 'This Category Does not Exist')
        return redirect('ecommercial/home')

def product(request, pk):
    product = Product.objects.get(id=pk)
    return render(request, 'ecommercial/product.html', {'product': product})

def home(request):
    products = Product.objects.all()
    return render(request, 'ecommercial/home.html', {'products': products})


def about(request):
    return render(request, 'ecommercial/about.html', {})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('ecommercial:home')
        else:
            messages.success(request, 'The username and password do not match!')
            return redirect('ecommercial:login')

    else:
        return render(request, 'ecommercial/login.html', {} )


def logout_user(request):
    logout(request)
    messages.success(request, ('You have been logged out.'))
    return redirect("ecommercial:home")


def register_user(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # Login user.
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ('Username created successfully- Please fill in your user info below...'))
            return redirect('ecommercial:update_info')
        else:
            messages.success(request, ('There was a problem during the registration, please try again!.'))
            return redirect('ecommercial:register')
    else:
        return render(request, 'ecommercial/register.html', {'form':form})


def search(request):
    return render(request, 'ecommercial/search.html', {})

ecommercial/templates/ecommercial/category.html
{% extends 'ecommercial/base.html' %}

{% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">{{ category }</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Category Page}</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">


                    {% for product in products %}
                        {% if product.is_sale %}
                         <div class="col mb-5">
                        <div class="card h-100">
                             <!-- Sale badge-->
                            <div class="badge bg-light
                                text-black position-absolute"
                                 style="top: 0.5rem; right: 0.5rem">Sale
                            </div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}"..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product price-->

                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small
                                        text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>

                                    <strike>
                                        ${{ product.price }}
                                    </strike>
                                    &nbsp;
                                    ${{ product.sale_price }}
                                    <br/>
                                    In: {{ product.category }}
                                    <br/>

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                            href="{% url 'ecommercial:product' product.id %}">View Product</a></div>
                            </div>
                        </div>
                    </div>
                        {% else %}
                        <div class="col mb-5">
                            <div class="card h-100">

                                <!-- Product image-->
                                <img class="card-img-top" src="{{ product.image.url }}"..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ product.name }}</h5>
                                        <!-- Product price-->

                                        <!-- Product reviews-->
                                        <div class="d-flex justify-content-center small
                                            text-warning mb-2">
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                        </div>
                                        ${{ product.price }}
                                        <br/>
                                        In: {{ product.category }}
                                        <br/>

                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                            href="{% url 'ecommercial:product' product.id %}">View Product</a></div>
                                </div>
                            </div>
                        </div>

                        {% endif %}
                    {% endfor %}

            </div>
        </section>

{% endblock content %}

ecommercial/templates/ecommercial/category_summary.html
{% extends 'ecommercial/base.html' %}
{% block content %}

<!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Categories</h1>
                <p class="lead fw-normal text-white-50 mb-0"
                >Choose Your Category Below...</p>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    {% for category in categories %}
                    <h3><a href="{% url 'ecommercial:category' category %}">{{ category }}</a></h3>
                    {% endfor %}

                    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
                </div>
            </center>
        </div>
    </div>

{% endblock content %}

ecommercial/templates/ecommercial/home.html
{% extends 'ecommercial/base.html' %}

{% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Welcome to Derrick Pets</h1>
                    <p class="lead fw-normal text-white-50 mb-0">The place to find your Pet</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">


                    {% for product in products %}
                        {% if product.is_sale %}
                         <div class="col mb-5">
                        <div class="card h-100">
                             <!-- Sale badge-->
                            <div class="badge bg-light
                                text-black position-absolute"
                                 style="top: 0.5rem; right: 0.5rem">Sale
                            </div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}"..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product price-->

                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small
                                        text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>

                                    <strike>
                                        ${{ product.price }}
                                    </strike>
                                    &nbsp;
                                    ${{ product.sale_price }}
                                    <br/>
                                    In: {{ product.category }}
                                    <br/>

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                            href="{% url 'ecommercial:product' product.id %}">View Product</a></div>
                            </div>
                        </div>
                    </div>
                        {% else %}
                        <div class="col mb-5">
                            <div class="card h-100">

                                <!-- Product image-->
                                <img class="card-img-top" src="{{ product.image.url }}"..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ product.name }}</h5>
                                        <!-- Product price-->

                                        <!-- Product reviews-->
                                        <div class="d-flex justify-content-center small
                                            text-warning mb-2">
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                            <div class="bi-star-fill"></div>
                                        </div>
                                        ${{ product.price }}
                                        <br/>
                                        In: {{ product.category }}
                                        <br/>

                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                            href="{% url 'ecommercial:product' product.id %}">View Product</a></div>
                                </div>
                            </div>
                        </div>

                        {% endif %}
                    {% endfor %}

            </div>
        </section>

{% endblock content %}

ecommercial/templates/ecommercial/navbar.html
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'ecommercial:home' %}">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="
                        page" href="{% url 'ecommercial:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="
                        page" href="{% url 'ecommercial:search' %}">Search</a></li>
                        <li class="nav-item"><a class="
                        nav-link" href="{% url 'ecommercial:about' %}">About</a></li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'ecommercial:update_user' %}">User Profile</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'ecommercial:update_info' %}">User Info</a></li>
                            </ul>
                    </li>



                    <li class="nav-item"><a class="
                    nav-link" href="{% url 'ecommercial:logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="
                    nav-link" href="{% url 'ecommercial:login' %}">Login</a></li>

                    <li class="nav-item"><a class="
                    nav-link" href="{% url 'ecommercial:register' %}">Register</a></li>

                {% endif %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'ecommercial:category_summary' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'ecommercial:category' 'Dogs' %}">Dogs</a></li>
                                <li><a class="dropdown-item" href="{% url 'ecommercial:category' 'Cats' %}">Cats</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
        <a href="{% url 'cart:cart_summary' %}" class="btn btn-outline-dark">
            <i class="bi-cart-fill me-1"></i>
                    Cart
        <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length}}</span></a>

                    </form>
                </div>
            </div>
        </nav>